package ProductDescription.behavior;

/*Generated by MPS */

import com.mbeddr.core.expressions.behavior.Expression_BehaviorDescriptor;

public class AttributeRef_BehaviorDescriptor extends Expression_BehaviorDescriptor {
  public AttributeRef_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "ProductDescription.structure.AttributeRef";
  }
}
