package ProductDescription.behavior;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BehaviorDescriptor;
import java.util.Arrays;
import jetbrains.mps.smodel.runtime.interpreted.BehaviorAspectInterpreted;

public class BehaviorAspectDescriptor implements jetbrains.mps.smodel.runtime.BehaviorAspectDescriptor {
  private static String[] stringSwitchCases_846f5o_a0a0a = new String[]{"ProductDescription.structure.Attribute", "ProductDescription.structure.AttributeRef", "ProductDescription.structure.ContractType", "ProductDescription.structure.Date", "ProductDescription.structure.ProductDescription", "ProductDescription.structure.ProductReference", "ProductDescription.structure.ProductTestSuite", "ProductDescription.structure.SimpleProduct", "ProductDescription.structure.StringWrapper", "ProductDescription.structure.TestCase"};

  public BehaviorAspectDescriptor() {
  }

  public BehaviorDescriptor getDescriptor(String fqName) {
    switch (Arrays.binarySearch(stringSwitchCases_846f5o_a0a0a, fqName)) {
      case 4:
        return new ProductDescription_BehaviorDescriptor();
      case 2:
        return new ContractType_BehaviorDescriptor();
      case 3:
        return new Date_BehaviorDescriptor();
      case 5:
        return new ProductReference_BehaviorDescriptor();
      case 7:
        return new SimpleProduct_BehaviorDescriptor();
      case 0:
        return new Attribute_BehaviorDescriptor();
      case 1:
        return new AttributeRef_BehaviorDescriptor();
      case 6:
        return new ProductTestSuite_BehaviorDescriptor();
      case 9:
        return new TestCase_BehaviorDescriptor();
      case 8:
        return new StringWrapper_BehaviorDescriptor();
      default:
        return BehaviorAspectInterpreted.getInstance().getDescriptor(fqName);
    }
  }
}
