package ProductDescription.behavior;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SConceptOperations;
import java.util.List;
import jetbrains.mps.internal.collections.runtime.ListSequence;

public class CompositeProductType_Behavior {
  public static void init(SNode thisNode) {
    SLinkOperations.setTarget(thisNode, "rateCalculation", SConceptOperations.createNewNode("ProductDescription.structure.ResultExpression", null), true);
  }

  public static void virtual_allAttributes_3975765255154863205(SNode thisNode, List<SNode> attrs) {
    ProductType_Behavior.callSuper_allAttributes_3975765255154863205(thisNode, "ProductDescription.structure.CompositeProductType", attrs);
    for (SNode cp : ListSequence.fromList(SLinkOperations.getTargets(thisNode, "containedProducts", true))) {
      ProductType_Behavior.call_allAttributes_3975765255154863205(SLinkOperations.getTarget(cp, "pt", false), attrs);
    }
  }
}
