package ProductDescription.behavior;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import java.util.List;

public class CompositeProductType_BehaviorDescriptor extends ProductType_BehaviorDescriptor {
  public CompositeProductType_BehaviorDescriptor() {
  }

  public void virtual_allAttributes_3975765255154863205(SNode thisNode, List<SNode> attrs) {
    CompositeProductType_Behavior.virtual_allAttributes_3975765255154863205(thisNode, attrs);
  }

  @Override
  public String getConceptFqName() {
    return "ProductDescription.structure.CompositeProductType";
  }
}
