package ProductDescription.behavior;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import java.util.List;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.smodel.structure.BehaviorDescriptor;
import jetbrains.mps.smodel.structure.ConceptRegistry;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.smodel.behaviour.BehaviorManager;

public class ProductType_Behavior {
  private static Class[] PARAMETERS_3975765255154863205 = {SNode.class, List.class};

  public static void init(SNode thisNode) {
  }

  public static void virtual_allAttributes_3975765255154863205(SNode thisNode, List<SNode> attrs) {
    ListSequence.fromList(attrs).addSequence(ListSequence.fromList(SLinkOperations.getTargets(thisNode, "attributes", true)));
  }

  public static void call_allAttributes_3975765255154863205(SNode thisNode, List<SNode> attrs) {
    BehaviorDescriptor descriptor = ConceptRegistry.getInstance().getBehaviorDescriptorForInstanceNode(thisNode);
    descriptor.invoke(Object.class, SNodeOperations.cast(thisNode, "ProductDescription.structure.ProductType"), "virtual_allAttributes_3975765255154863205", PARAMETERS_3975765255154863205, attrs);
  }

  public static void callSuper_allAttributes_3975765255154863205(SNode thisNode, String callerConceptFqName, List<SNode> attrs) {
    BehaviorManager.getInstance().invokeSuper(Object.class, SNodeOperations.cast(thisNode, "ProductDescription.structure.ProductType"), callerConceptFqName, "virtual_allAttributes_3975765255154863205", PARAMETERS_3975765255154863205, attrs);
  }
}
