package ProductDescription.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class ProductTypeRef_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public ProductTypeRef_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "ProductDescription.structure.ProductTypeRef";
  }
}
