package ProductDescription.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class ProductTestSuite_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public ProductTestSuite_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "ProductDescription.structure.ProductTestSuite";
  }
}
