package ProductDescription.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class ProductReference_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public ProductReference_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "ProductDescription.structure.ProductReference";
  }
}
