package ProductDescription.behavior;

/*Generated by MPS */

import com.mbeddr.core.expressions.behavior.Expression_BehaviorDescriptor;

public class ResultExpression_BehaviorDescriptor extends Expression_BehaviorDescriptor {
  public ResultExpression_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "ProductDescription.structure.ResultExpression";
  }
}
