package ProductDescription.behavior;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SConceptOperations;
import java.util.Set;
import java.util.HashSet;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class SimpleProduct_Behavior {
  public static void init(SNode thisNode) {
    SLinkOperations.setTarget(thisNode, "rateCalculation", SConceptOperations.createNewNode("com.mbeddr.core.statements.structure.StatementList", null), true);
    SLinkOperations.setTarget(thisNode, "type", new SimpleProduct_Behavior.QuotationClass_wqh4gq_a2a1a0().createNode(), true);
  }

  public static SNode virtual_getStatementList_8105003328814797304(SNode thisNode) {
    return SLinkOperations.getTarget(thisNode, "rateCalculation", true);
  }

  public static class QuotationClass_wqh4gq_a2a1a0 {
    public QuotationClass_wqh4gq_a2a1a0() {
    }

    public SNode createNode() {
      SNode result = null;
      Set<SNode> _parameterValues_129834374 = new HashSet<SNode>();
      SNode quotedNode_1 = null;
      {
        quotedNode_1 = SModelUtil_new.instantiateConceptDeclaration("com.mbeddr.core.expressions.structure.Int64tType", null, GlobalScope.getInstance(), false);
        SNode quotedNode1_2 = quotedNode_1;
        result = quotedNode1_2;
      }
      return result;
    }
  }
}
