package ProductDescription.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.INamedConcept_BehaviorDescriptor;

public class SimpleProduct_BehaviorDescriptor extends ProductType_BehaviorDescriptor implements INamedConcept_BehaviorDescriptor {
  public SimpleProduct_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "ProductDescription.structure.SimpleProduct";
  }
}
