package ProductDescription.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.INamedConcept_BehaviorDescriptor;
import com.mbeddr.core.modules.behavior.IFunctionLike_BehaviorDescriptor;
import jetbrains.mps.smodel.SNode;
import com.mbeddr.core.base.behavior.IIdentifierNamedConcept_Behavior;

public class SimpleProduct_BehaviorDescriptor extends ProductType_BehaviorDescriptor implements INamedConcept_BehaviorDescriptor, IFunctionLike_BehaviorDescriptor {
  public SimpleProduct_BehaviorDescriptor() {
  }

  public String virtual_shortDescriptionForCCMenu_5470497459578304992(SNode thisNode) {
    return IIdentifierNamedConcept_Behavior.virtual_shortDescriptionForCCMenu_5470497459578304992(thisNode);
  }

  public String virtual_conceptLabel_5470497459580078362(SNode thisNode) {
    return IIdentifierNamedConcept_Behavior.virtual_conceptLabel_5470497459580078362(thisNode);
  }

  public String virtual_qualifiedName_5470497459578244269(SNode thisNode) {
    return IIdentifierNamedConcept_Behavior.virtual_qualifiedName_5470497459578244269(thisNode);
  }

  public SNode virtual_getStatementList_8105003328814797304(SNode thisNode) {
    return SimpleProduct_Behavior.virtual_getStatementList_8105003328814797304(thisNode);
  }

  @Override
  public String getConceptFqName() {
    return "ProductDescription.structure.SimpleProduct";
  }
}
