package ProductDescription.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class StringWrapper_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public StringWrapper_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "ProductDescription.structure.StringWrapper";
  }
}
