package ProductDescription.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class TestCase_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public TestCase_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "ProductDescription.structure.TestCase";
  }
}
