package ProductDescription.behavior;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SConceptOperations;

public class TestCase_Behavior {
  public static void init(SNode thisNode) {
  }

  public static void call_initialize_1850134002004986963(SNode thisNode, int paramCount) {
    for (int i = 0; i < paramCount; i++) {
      ListSequence.fromList(SLinkOperations.getTargets(thisNode, "inputValues", true)).addElement(SConceptOperations.createNewNode("com.mbeddr.core.expressions.structure.Expression", null));
    }
    SLinkOperations.setNewChild(thisNode, "expectedResult", "com.mbeddr.core.expressions.structure.Expression");
  }
}
