package ProductDescription.typesystem;

/*Generated by MPS */

import jetbrains.mps.lang.typesystem.runtime.AbstractInferenceRule_Runtime;
import jetbrains.mps.lang.typesystem.runtime.InferenceRule_Runtime;
import jetbrains.mps.smodel.SNode;
import jetbrains.mps.typesystem.inference.TypeCheckingContext;
import jetbrains.mps.lang.typesystem.runtime.IsApplicableStatus;
import jetbrains.mps.typesystem.inference.EquationInfo;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.smodel.SModelUtil_new;

public class typeof_AttributeRef_InferenceRule extends AbstractInferenceRule_Runtime implements InferenceRule_Runtime {
  public typeof_AttributeRef_InferenceRule() {
  }

  public void applyRule(final SNode ar, final TypeCheckingContext typeCheckingContext, IsApplicableStatus status) {
    {
      SNode _nodeToCheck_1029348928467 = ar;
      EquationInfo _info_12389875345 = new EquationInfo(_nodeToCheck_1029348928467, null, "r:a843dbff-e2d6-4d50-a0a3-752640797e15(ProductDescription.typesystem)", "6991865057876569378", 0, null);
      typeCheckingContext.createEquation((SNode) typeCheckingContext.typeOf(_nodeToCheck_1029348928467, "r:a843dbff-e2d6-4d50-a0a3-752640797e15(ProductDescription.typesystem)", "6991865057876569373", true), (SNode) typeCheckingContext.typeOf(SLinkOperations.getTarget(ar, "attr", false), "r:a843dbff-e2d6-4d50-a0a3-752640797e15(ProductDescription.typesystem)", "6991865057876569383", true), _info_12389875345);
    }
  }

  public String getApplicableConceptFQName() {
    return "ProductDescription.structure.AttributeRef";
  }

  public IsApplicableStatus isApplicableAndPattern(SNode argument) {
    {
      boolean b = SModelUtil_new.isAssignableConcept(argument.getConceptFqName(), this.getApplicableConceptFQName());
      return new IsApplicableStatus(b, null);
    }
  }

  public boolean overrides() {
    return false;
  }
}
