package ProductDescription.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.DefaultNodeEditor;
import jetbrains.mps.nodeEditor.cells.EditorCell;
import jetbrains.mps.nodeEditor.EditorContext;
import jetbrains.mps.smodel.SNode;
import jetbrains.mps.nodeEditor.cells.EditorCell_Collection;
import jetbrains.mps.nodeEditor.cells.EditorCell_Constant;
import jetbrains.mps.nodeEditor.cells.EditorCell_Indent;
import jetbrains.mps.lang.editor.table.runtime.TableModelCreator;
import jetbrains.mps.lang.editor.table.runtime.TableModel;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.lang.editor.table.runtime.EditorCell_Table;
import jetbrains.mps.nodeEditor.style.Style;
import jetbrains.mps.nodeEditor.style.StyleAttributes;

public class ProductTestSuite_Editor extends DefaultNodeEditor {
  public EditorCell createEditorCell(EditorContext editorContext, SNode node) {
    return this.createCollection_m3bw6i_a(editorContext, node);
  }

  private EditorCell createCollection_m3bw6i_a(EditorContext editorContext, SNode node) {
    EditorCell_Collection editorCell = EditorCell_Collection.createVertical(editorContext, node);
    editorCell.setCellId("Collection_m3bw6i_a");
    editorCell.addEditorCell(this.createConstant_m3bw6i_a0(editorContext, node));
    editorCell.addEditorCell(this.createCollection_m3bw6i_b0(editorContext, node));
    return editorCell;
  }

  private EditorCell createCollection_m3bw6i_b0(EditorContext editorContext, SNode node) {
    EditorCell_Collection editorCell = EditorCell_Collection.createHorizontal(editorContext, node);
    editorCell.setCellId("Collection_m3bw6i_b0");
    editorCell.addEditorCell(this.createIndentCell_m3bw6i_a1a(editorContext, node));
    editorCell.addEditorCell(this.createTable_m3bw6i_b1a(editorContext, node));
    return editorCell;
  }

  private EditorCell createConstant_m3bw6i_a0(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, "tests");
    editorCell.setCellId("Constant_m3bw6i_a0");
    editorCell.setDefaultText("");
    return editorCell;
  }

  private EditorCell createIndentCell_m3bw6i_a1a(EditorContext editorContext, SNode node) {
    EditorCell_Indent result = new EditorCell_Indent(editorContext, node);
    return result;
  }

  private EditorCell createTable_m3bw6i_b1a(EditorContext editorContext, SNode node) {
    TableModelCreator creator = new TableModelCreator() {
      public TableModel getTable(final SNode node, final EditorContext editorContext) {
        return new ProductTestSuiteTableModel(SNodeOperations.cast(SNodeOperations.getParent(node), "ProductDescription.structure.SimpleProduct"), editorContext);
      }
    };
    EditorCell_Collection editorCell = EditorCell_Table.createTable(editorContext, node, creator.getTable(node, editorContext), "Table_m3bw6i_b1a");
    editorCell.setCellId("Table_m3bw6i_b1a_0");
    {
      Style style = editorCell.getStyle();
      style.set(StyleAttributes.INDENT_LAYOUT_NEW_LINE, true);
      style.set(StyleAttributes.INDENT_LAYOUT_ON_NEW_LINE, true);
    }
    return editorCell;
  }
}
