package ProductDescription.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;
import jetbrains.mps.smodel.SNodePointer;
import java.util.Map;
import jetbrains.mps.smodel.runtime.ReferenceConstraintsDescriptor;
import java.util.HashMap;
import jetbrains.mps.smodel.runtime.base.BaseReferenceConstraintsDescriptor;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.runtime.ReferenceScopeProvider;
import jetbrains.mps.smodel.runtime.base.BaseReferenceScopeProvider;
import jetbrains.mps.smodel.IOperationContext;
import jetbrains.mps.smodel.runtime.ReferenceConstraintsContext;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SModelOperations;

public class ProductReference_Constraints extends BaseConstraintsDescriptor {
  private static SNodePointer breakingNode_seubbd_a0a1a0a0a1a0b0a1a0 = new SNodePointer("r:89e43441-0eca-4516-8961-73d762600492(ProductDescription.constraints)", "6991865057876526355");

  public ProductReference_Constraints() {
    super("ProductDescription.structure.ProductReference");
  }

  @Override
  protected Map<String, ReferenceConstraintsDescriptor> getNotDefaultReferences() {
    Map<String, ReferenceConstraintsDescriptor> references = new HashMap();
    references.put("product", new BaseReferenceConstraintsDescriptor("product", this) {
      @Override
      public boolean hasOwnScopeProvider() {
        return true;
      }

      @Nullable
      @Override
      public ReferenceScopeProvider getScopeProvider() {
        return new BaseReferenceScopeProvider() {
          @Override
          public Object createSearchScopeOrListOfNodes(final IOperationContext operationContext, final ReferenceConstraintsContext _context) {
            return SModelOperations.getRootsIncludingImported(_context.getModel(), operationContext.getScope(), "ProductDescription.structure.ProductType");
          }

          @Override
          public SNodePointer getSearchScopeValidatorNode() {
            return breakingNode_seubbd_a0a1a0a0a1a0b0a1a0;
          }
        };
      }
    });
    return references;
  }
}
