package ProductDescription.structure;

/*Generated by MPS */

import com.mbeddr.core.expressions.structure.Expression;
import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class AttributeRef extends Expression {
  public static final String concept = "ProductDescription.structure.AttributeRef";
  public static final String ATTR = "attr";

  public AttributeRef(SNode node) {
    super(node);
  }

  public Attribute getAttr() {
    return (Attribute) this.getReferent(Attribute.class, AttributeRef.ATTR);
  }

  public void setAttr(Attribute node) {
    super.setReferent(AttributeRef.ATTR, node);
  }

  public static AttributeRef newInstance(SModel sm, boolean init) {
    return (AttributeRef) SModelUtil_new.instantiateConceptDeclaration("ProductDescription.structure.AttributeRef", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static AttributeRef newInstance(SModel sm) {
    return AttributeRef.newInstance(sm, false);
  }
}
