package ProductDescription.structure;

/*Generated by MPS */

import jetbrains.mps.lang.core.structure.BaseConcept;
import jetbrains.mps.lang.core.structure.INamedConcept;
import jetbrains.mps.smodel.SNode;
import java.util.Iterator;
import java.util.List;
import jetbrains.mps.lang.core.structure.Attribute;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class ProductDescription extends BaseConcept implements INamedConcept {
  public static final String concept = "ProductDescription.structure.ProductDescription";
  public static final String NAME = "name";
  public static final String SHORT_DESCRIPTION = "shortDescription";
  public static final String ALIAS = "alias";
  public static final String VIRTUAL_PACKAGE = "virtualPackage";
  public static final String VALID_FROM = "validFrom";
  public static final String VALID_TO = "validTo";
  public static final String CONTRACT_TYPES = "contractTypes";
  public static final String SMODEL_ATTRIBUTE = "smodelAttribute";

  public ProductDescription(SNode node) {
    super(node);
  }

  public String getName() {
    return this.getProperty(ProductDescription.NAME);
  }

  public void setName(String value) {
    this.setProperty(ProductDescription.NAME, value);
  }

  public String getShortDescription() {
    return this.getProperty(ProductDescription.SHORT_DESCRIPTION);
  }

  public void setShortDescription(String value) {
    this.setProperty(ProductDescription.SHORT_DESCRIPTION, value);
  }

  public String getAlias() {
    return this.getProperty(ProductDescription.ALIAS);
  }

  public void setAlias(String value) {
    this.setProperty(ProductDescription.ALIAS, value);
  }

  public String getVirtualPackage() {
    return this.getProperty(ProductDescription.VIRTUAL_PACKAGE);
  }

  public void setVirtualPackage(String value) {
    this.setProperty(ProductDescription.VIRTUAL_PACKAGE, value);
  }

  public Date getValidFrom() {
    return (Date) this.getChild(Date.class, ProductDescription.VALID_FROM);
  }

  public void setValidFrom(Date node) {
    super.setChild(ProductDescription.VALID_FROM, node);
  }

  public Date getValidTo() {
    return (Date) this.getChild(Date.class, ProductDescription.VALID_TO);
  }

  public void setValidTo(Date node) {
    super.setChild(ProductDescription.VALID_TO, node);
  }

  public int getContractTypesesCount() {
    return this.getChildCount(ProductDescription.CONTRACT_TYPES);
  }

  public Iterator<ContractType> contractTypeses() {
    return this.children(ContractType.class, ProductDescription.CONTRACT_TYPES);
  }

  public List<ContractType> getContractTypeses() {
    return this.getChildren(ContractType.class, ProductDescription.CONTRACT_TYPES);
  }

  public void addContractTypes(ContractType node) {
    this.addChild(ProductDescription.CONTRACT_TYPES, node);
  }

  public void insertContractTypes(ContractType prev, ContractType node) {
    this.insertChild(prev, ProductDescription.CONTRACT_TYPES, node);
  }

  public int getSmodelAttributesCount() {
    return this.getChildCount(ProductDescription.SMODEL_ATTRIBUTE);
  }

  public Iterator<Attribute> smodelAttributes() {
    return this.children(Attribute.class, ProductDescription.SMODEL_ATTRIBUTE);
  }

  public List<Attribute> getSmodelAttributes() {
    return this.getChildren(Attribute.class, ProductDescription.SMODEL_ATTRIBUTE);
  }

  public void addSmodelAttribute(Attribute node) {
    this.addChild(ProductDescription.SMODEL_ATTRIBUTE, node);
  }

  public void insertSmodelAttribute(Attribute prev, Attribute node) {
    this.insertChild(prev, ProductDescription.SMODEL_ATTRIBUTE, node);
  }

  public static ProductDescription newInstance(SModel sm, boolean init) {
    return (ProductDescription) SModelUtil_new.instantiateConceptDeclaration("ProductDescription.structure.ProductDescription", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static ProductDescription newInstance(SModel sm) {
    return ProductDescription.newInstance(sm, false);
  }
}
