package ProductDescription.structure;

/*Generated by MPS */

import jetbrains.mps.project.structure.modules.ModuleReference;
import jetbrains.mps.smodel.Language;
import jetbrains.mps.smodel.MPSModuleRepository;

public class ProductDescription_Language {
  public static ModuleReference MODULE_REFERENCE = ModuleReference.fromString("931d8873-6441-454f-bb23-5d8f8e84a6f8(ProductDescription)");

  public static Language get() {
    return (Language) MPSModuleRepository.getInstance().getModule(MODULE_REFERENCE);
  }
}
