package ProductDescription.structure;

/*Generated by MPS */

import jetbrains.mps.lang.core.structure.BaseConcept;
import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class ProductTypeRef extends BaseConcept {
  public static final String concept = "ProductDescription.structure.ProductTypeRef";
  public static final String PT = "pt";

  public ProductTypeRef(SNode node) {
    super(node);
  }

  public ProductType getPt() {
    return (ProductType) this.getReferent(ProductType.class, ProductTypeRef.PT);
  }

  public void setPt(ProductType node) {
    super.setReferent(ProductTypeRef.PT, node);
  }

  public static ProductTypeRef newInstance(SModel sm, boolean init) {
    return (ProductTypeRef) SModelUtil_new.instantiateConceptDeclaration("ProductDescription.structure.ProductTypeRef", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static ProductTypeRef newInstance(SModel sm) {
    return ProductTypeRef.newInstance(sm, false);
  }
}
