package ProductDescription.structure;

/*Generated by MPS */

import com.mbeddr.core.expressions.structure.Expression;
import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class ResultExpression extends Expression {
  public static final String concept = "ProductDescription.structure.ResultExpression";

  public ResultExpression(SNode node) {
    super(node);
  }

  public static ResultExpression newInstance(SModel sm, boolean init) {
    return (ResultExpression) SModelUtil_new.instantiateConceptDeclaration("ProductDescription.structure.ResultExpression", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static ResultExpression newInstance(SModel sm) {
    return ResultExpression.newInstance(sm, false);
  }
}
