package ProductDescription.structure;

/*Generated by MPS */

import jetbrains.mps.lang.core.structure.INamedConcept;
import jetbrains.mps.smodel.SNode;
import java.util.Iterator;
import jetbrains.mps.lang.core.structure.Attribute;
import java.util.List;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class SimpleProductType extends ProductType implements INamedConcept {
  public static final String concept = "ProductDescription.structure.SimpleProductType";
  public static final String NAME = "name";
  public static final String SHORT_DESCRIPTION = "shortDescription";
  public static final String ALIAS = "alias";
  public static final String VIRTUAL_PACKAGE = "virtualPackage";
  public static final String SMODEL_ATTRIBUTE = "smodelAttribute";

  public SimpleProductType(SNode node) {
    super(node);
  }

  public String getName() {
    return this.getProperty(SimpleProductType.NAME);
  }

  public void setName(String value) {
    this.setProperty(SimpleProductType.NAME, value);
  }

  public String getShortDescription() {
    return this.getProperty(SimpleProductType.SHORT_DESCRIPTION);
  }

  public void setShortDescription(String value) {
    this.setProperty(SimpleProductType.SHORT_DESCRIPTION, value);
  }

  public String getAlias() {
    return this.getProperty(SimpleProductType.ALIAS);
  }

  public void setAlias(String value) {
    this.setProperty(SimpleProductType.ALIAS, value);
  }

  public String getVirtualPackage() {
    return this.getProperty(SimpleProductType.VIRTUAL_PACKAGE);
  }

  public void setVirtualPackage(String value) {
    this.setProperty(SimpleProductType.VIRTUAL_PACKAGE, value);
  }

  public int getSmodelAttributesCount() {
    return this.getChildCount(SimpleProductType.SMODEL_ATTRIBUTE);
  }

  public Iterator<Attribute> smodelAttributes() {
    return this.children(Attribute.class, SimpleProductType.SMODEL_ATTRIBUTE);
  }

  public List<Attribute> getSmodelAttributes() {
    return this.getChildren(Attribute.class, SimpleProductType.SMODEL_ATTRIBUTE);
  }

  public void addSmodelAttribute(Attribute node) {
    this.addChild(SimpleProductType.SMODEL_ATTRIBUTE, node);
  }

  public void insertSmodelAttribute(Attribute prev, Attribute node) {
    this.insertChild(prev, SimpleProductType.SMODEL_ATTRIBUTE, node);
  }

  public static SimpleProductType newInstance(SModel sm, boolean init) {
    return (SimpleProductType) SModelUtil_new.instantiateConceptDeclaration("ProductDescription.structure.SimpleProductType", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static SimpleProductType newInstance(SModel sm) {
    return SimpleProductType.newInstance(sm, false);
  }
}
