package ProductDescription.structure;

/*Generated by MPS */

import jetbrains.mps.lang.core.structure.BaseConcept;
import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class StringWrapper extends BaseConcept {
  public static final String concept = "ProductDescription.structure.StringWrapper";
  public static final String VALUE = "value";

  public StringWrapper(SNode node) {
    super(node);
  }

  public String getValue() {
    return this.getProperty(StringWrapper.VALUE);
  }

  public void setValue(String value) {
    this.setProperty(StringWrapper.VALUE, value);
  }

  public static StringWrapper newInstance(SModel sm, boolean init) {
    return (StringWrapper) SModelUtil_new.instantiateConceptDeclaration("ProductDescription.structure.StringWrapper", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static StringWrapper newInstance(SModel sm) {
    return StringWrapper.newInstance(sm, false);
  }
}
